# ---------------------------------------------------------------
# python best courses https://courses.tanpham.org/
# ---------------------------------------------------------------

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [87]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [88]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [89]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [90]:
x.size * x.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [91]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [92]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [93]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [94]:
x = np.arange(10)
x = x[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [95]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [96]:
x = np.nonzero([1, 2, 0, 0, 4, 0])
x

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [97]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [98]:
x = np.random.random((3, 3, 3))
x

array([[[0.69187885, 0.88467111, 0.24341838],
        [0.55790017, 0.58075276, 0.10985486],
        [0.80825603, 0.25055174, 0.30119213]],

       [[0.53040686, 0.39987845, 0.01907941],
        [0.05579969, 0.58486556, 0.43861486],
        [0.40694089, 0.39695994, 0.77201606]],

       [[0.32364301, 0.85674239, 0.13422537],
        [0.8530194 , 0.13563947, 0.84472315],
        [0.81691975, 0.68918361, 0.05931958]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [99]:
x = np.random.random((10, 10))
_min = x.min()
_max = x.max()
(_min, _max)

(0.016065121461361187, 0.985221203167181)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [100]:
x = np.random.random(30)
_mean = x.mean()
_mean

0.5126320030983436

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [101]:
x = np.ones((10, 10))
x[1: -1, 1: -1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [102]:
x = np.ones((5, 5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [103]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [104]:
x = np.diag(1 + np.arange(4), k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [105]:
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [106]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [107]:
x = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [108]:
x = np.random.random((5, 5))
_min = x.min()
_max = x.max()
x = (x - _min) / (_max - _min)
x

array([[0.80689807, 0.13453004, 0.60111652, 0.73969307, 0.10676171],
       [0.51461097, 0.4899615 , 0.69590586, 0.7387042 , 0.14223561],
       [0.96127741, 1.        , 0.09568842, 0.82897692, 0.85736162],
       [0.21750745, 0.90603256, 0.44252483, 0.34417951, 0.52575689],
       [0.        , 0.99906277, 0.4589231 , 0.20784552, 0.43740194]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [109]:
x = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
x

/tmp/ipykernel_17245/319242291.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [110]:
x = np.dot(np.ones((5, 3)), np.ones((3, 2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [111]:
x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [112]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [113]:
"""Z**Z
2 << Z >> 2
1j*Z
Z/1/1"""

'Z**Z\n2 << Z >> 2\n1j*Z\nZ/1/1'

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [114]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_17245/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_17245/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_17245/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [115]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ 7., -1.,  1.,  7.,  1., -9., -9., -4., -9., -9.])

#### 30. How to find common values between two arrays? (★☆☆)

In [116]:
x_1 = np.random.randint(0,10,10)
x_2 = np.random.randint(0,10,10)
np.intersect1d(x_1, x_2)

array([1, 7, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [117]:
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0

_ = np.seterr(**defaults)
x

array([inf])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [118]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_17245/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [119]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [120]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [121]:
A = np.ones(2)*1
B = np.ones(2)*2
C = np.ones(2)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [122]:
x = np.random.uniform(0, 10, 10)
print(x)
print (x - x%1)
print (np.floor(x))
print (np.ceil(x)-1)
print (x.astype(int))
print (np.trunc(x))

[3.50879915 9.63986519 5.63296194 9.54586742 9.42601379 8.40996249
 9.51894665 1.17140873 2.72573107 7.99587544]
[3. 9. 5. 9. 9. 8. 9. 1. 2. 7.]
[3. 9. 5. 9. 9. 8. 9. 1. 2. 7.]
[3. 9. 5. 9. 9. 8. 9. 1. 2. 7.]
[3 9 5 9 9 8 9 1 2 7]
[3. 9. 5. 9. 9. 8. 9. 1. 2. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [123]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [124]:
def generator():
    for i in range(10):
        yield i

x = np.fromiter(generator(), dtype=float, count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [125]:
x = np.linspace(0, 1, 11, endpoint=False)
x = x[1: ]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [126]:
x = np.random.random(10)
x.sort()
x

array([0.05107919, 0.09080853, 0.21672239, 0.26721456, 0.31161415,
       0.40505442, 0.78574644, 0.9641542 , 0.96462561, 0.97376329])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [127]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [128]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
equal

True

#### 43. Make an array immutable (read-only) (★★☆)

In [129]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [130]:
x = np.random.random((10, 2))
y = x[:, 0]
z = x[:, 1]

r = np.sqrt(y**2 + z**2)
t = np.arctan2(y, z)
r, t

(array([0.94887667, 0.85185327, 0.84728919, 0.97429436, 1.03891392,
        0.88950585, 0.84352028, 0.56449036, 0.83197093, 1.32965618]),
 array([0.98504115, 0.61419838, 0.85487164, 1.30106672, 0.54072878,
        0.04462966, 0.97142249, 0.62587215, 1.3886881 , 0.82800864]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [131]:
x = np.random.random(10)
x[x.argmax()] = 0
x

array([0.00314777, 0.        , 0.82436011, 0.29479804, 0.64499539,
       0.18244412, 0.38325931, 0.76950961, 0.19183403, 0.08200428])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [132]:
x = np.zeros((5, 5), [('x', float), ('y', float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
x

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [133]:
x = np.arange(8)
y = x + 0.5

c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

3638.1636371179666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [134]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [135]:
x = np.zeros((4, 4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [136]:
x = np.arange(100)
vector = np.random.uniform(0, 100)
index = (np.abs(x - vector)).argmin()
x[index]

59

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [137]:
structured_array = np.zeros(10, [ ('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
structured_array

/tmp/ipykernel_17245/4271667400.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  structured_array = np.zeros(10, [ ('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [138]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0], z[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
d

array([[0.        , 0.72885938, 0.45905863, 0.58984256, 0.68795571,
        0.85380727, 0.88115563, 0.91336064, 0.43353257, 0.24839693],
       [0.72885938, 0.        , 0.66104588, 0.29864422, 0.33193653,
        0.39073966, 0.64420716, 0.7878415 , 0.35149765, 0.52319139],
       [0.45905863, 0.66104588, 0.        , 0.37624335, 0.41585121,
        0.55088725, 0.46167739, 0.46093521, 0.33061658, 0.52595791],
       [0.58984256, 0.29864422, 0.37624335, 0.        , 0.10614398,
        0.26831624, 0.40683908, 0.52511545, 0.15974429, 0.47633897],
       [0.68795571, 0.33193653, 0.41585121, 0.10614398, 0.        ,
        0.16588339, 0.32233736, 0.45749715, 0.26394798, 0.58248204],
       [0.85380727, 0.39073966, 0.55088725, 0.26831624, 0.16588339,
        0.        , 0.2851327 , 0.44390344, 0.4279815 , 0.74113895],
       [0.88115563, 0.64420716, 0.46167739, 0.40683908, 0.32233736,
        0.2851327 , 0.        , 0.15983784, 0.52948779, 0.84766312],
       [0.91336064, 0.7878415 , 0.4609352

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [139]:
x = np.arange(10, dtype=np.int32)
x = x.astype(np.float32, copy=False)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [140]:
x = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(x):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [141]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d - mu)**2 / ( 2.0 * sigma**2 ) ) )
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [142]:
x = np.zeros((4,4))
np.put(x, np.random.choice(range(4*4), 2, replace=False),1)
x

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [143]:
x = np.random.rand(1, 10)
_mean = x - x.mean(axis=1, keepdims=True)
_mean

array([[-0.13791072, -0.27888925, -0.1214102 ,  0.29878272, -0.32781961,
         0.28691019,  0.27666716,  0.32920218,  0.09188033, -0.4174128 ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [144]:
x = np.random.randint(0, 10, (3, 3))
print(x)
print(x[x[:, 1].argsort()])

[[1 2 9]
 [0 5 7]
 [2 6 2]]
[[1 2 9]
 [0 5 7]
 [2 6 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [145]:
x = np.random.randint(0, 3, (3, 10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [147]:
x = np.random.uniform(0, 1, 10)
result = x.flat[np.abs(x - 0.5).argmin()]
result

0.5410721351442993

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [149]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)

_iterator = np.nditer([A,B,None])
for x,y,z in _iterator: z[...] = x + y
_iterator.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [150]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(10), "range_10")
x.name

'range_10'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [151]:
x = np.ones(10)
i = np.random.randint(0, len(x), 20)
x += np.bincount(i, minlength=len(x))
x

array([4., 3., 3., 3., 1., 4., 3., 1., 4., 4.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [152]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i, x)
f

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [153]:
x = np.random.randint(0, 2, (4, 4, 3)).astype(np.ubyte)
tmp = x[...,0]*(16*16) + x[...,1]*16 +x[...,2]
n = len(np.unique(tmp))
n

8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [154]:
x = np.random.randint(0, 10, (3, 4, 3, 4))
_sum = x.sum(axis=(-2,-1))
_sum

array([[51, 62, 50, 70],
       [61, 64, 55, 59],
       [47, 58, 63, 52]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [155]:
d = np.random.uniform(0, 1, 100)
s = np.random.randint(0, 10, 100)

d_means = np.bincount(s, weights=d) / np.bincount(s)
d_means

array([0.5978311 , 0.4536527 , 0.40448061, 0.47726097, 0.42655868,
       0.53855709, 0.53346305, 0.53979245, 0.44033056, 0.49867775])

#### 69. How to get the diagonal of a dot product? (★★★)

In [156]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))

np.diag(np.dot(A, B))

array([2.439366  , 1.32213671, 0.724284  , 1.0852169 , 1.20537381])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [157]:
x = np.array([1, 2, 3, 4, 5])
x_0 = np.zeros(len(x) + (len(x)-1)*(3))
x_0[:: 4] = x
x_0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [158]:
A = np.ones((5, 5, 3))
B = 2*np.ones((5, 5))
A * B[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [161]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
A

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [162]:
faces = np.random.randint(0, 100, (10, 3))
f = np.roll(faces.repeat(2,axis=1), -1, axis=1)
f = f.reshape(len(f)*3, 2)
f = np.sort(f, axis=1)
g = f.view(dtype=[('p0', f.dtype),('p1', f.dtype)])
g = np.unique(g)
g

array([( 2, 15), ( 2, 22), ( 9, 64), ( 9, 66), (14, 15), (14, 69),
       (15, 22), (15, 69), (19, 40), (19, 98), (24, 30), (24, 39),
       (24, 63), (24, 96), (27, 67), (27, 88), (30, 96), (38, 79),
       (38, 80), (39, 63), (40, 98), (61, 74), (61, 94), (64, 66),
       (67, 88), (74, 94), (78, 79), (78, 84), (79, 80), (79, 84)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [163]:
c = np.bincount([1, 1, 2, 3, 4, 4, 6])
x = np.repeat(np.arange(len(c)), c)
x

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [164]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

x = np.arange(20)
moving_average(x, n=3)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [165]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

x = rolling(np.arange(10), 3)
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [168]:
x = np.random.randint(0, 2, 100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0, 1.0, 100)
np.negative(x, out=x)

array([-7.20066287e-01,  3.97985964e-01,  8.14001601e-01, -7.81874518e-02,
       -5.30461722e-01,  5.12414014e-01,  5.39191893e-01,  4.53934396e-01,
       -9.45881850e-01, -9.48774485e-01,  4.20442477e-01,  9.38344862e-01,
       -9.70848252e-01,  2.79906741e-01,  7.79518800e-01, -4.78890170e-01,
        2.25831589e-01,  1.11146563e-02, -1.30090711e-01,  3.89968368e-01,
       -5.30601156e-01, -7.84303971e-01, -5.55120946e-01, -2.88292110e-01,
       -5.24020101e-01,  8.62374070e-01,  5.81643699e-01,  6.34110620e-01,
       -2.62292315e-01,  2.44727152e-01,  4.42011654e-01, -4.47985367e-02,
       -4.35586464e-02, -7.51935628e-01,  9.08191917e-01,  3.78044467e-01,
       -5.67659416e-01, -6.53663102e-01, -2.73981876e-01, -5.56254978e-01,
       -4.86718232e-01, -9.94917449e-01,  7.56810192e-01,  3.54121072e-01,
        5.55745143e-01, -7.71181768e-02, -4.30182410e-01, -9.96789597e-01,
       -2.37408753e-02,  2.97686708e-01, -8.93475939e-01,  8.05933938e-02,
       -4.93407172e-01, -

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [169]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

p0 = np.random.uniform(-10, 10, (10, 2))
p1 = np.random.uniform(-10, 10, (10, 2))
p  = np.random.uniform(-10, 10, (1, 2))
distance(p0, p1, p)

array([2.83520345, 0.91659925, 6.54408516, 5.46854731, 2.49780934,
       5.37908627, 3.26659653, 0.08059649, 7.59021253, 2.99498923])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [170]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
np.array([distance(P0,P1,p_i) for p_i in p])

array([[ 8.06519085, 11.67056241, 11.20946064,  2.40468804,  8.80259112,
         4.93316187,  1.8568664 ,  4.70800123,  0.84672615,  6.0175178 ],
       [ 1.44058467,  3.91299176,  3.5088803 ,  4.97578323,  1.02994024,
         7.12796548,  4.85749704,  2.48247011,  3.30663917,  0.14658521],
       [ 2.11535993, 13.31450265, 10.22108201,  7.11415691,  9.19878175,
         7.39330139, 10.08548658,  0.6186446 , 11.93026408,  1.67399527],
       [ 1.5866914 ,  3.795145  ,  2.34908729,  3.83606883,  0.41400927,
         2.44068895,  0.40329349,  4.82562911,  0.69103937,  3.49883819],
       [ 0.83343133,  4.27223605,  2.94590442,  3.53010074,  0.9508602 ,
         2.86355242,  0.75050249,  4.11942747,  0.46660265,  2.71752852],
       [11.91331537, 17.4172137 , 16.53646592,  8.32507206, 14.38022302,
         1.59874523,  1.99456423,  9.22602344,  5.39318551,  9.07946403],
       [ 2.36848497,  2.93035553,  3.16308455,  6.66647559,  0.34598526,
        10.25615828,  7.95443028,  2.04448831

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [179]:
x = np.arange(1, 15, dtype=np.uint32)
y = stride_tricks.as_strided(x, (11, 4), (4, 4))
y

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [180]:
x = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(x) 
rank = np.sum(S > 1e-10)
rank

10

#### 83. How to find the most frequent value in an array?

In [181]:
x = np.random.randint(0, 10, 50)
np.bincount(x).argmax()

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [183]:
x = np.random.randint(0, 5, (10, 10))
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
c = stride_tricks.as_strided(x, shape=(i, j, 3, 3), strides=x.strides + x.strides)
c

array([[[[0, 4, 0],
         [3, 0, 4],
         [0, 4, 0]],

        [[4, 0, 2],
         [0, 4, 0],
         [4, 0, 0]],

        [[0, 2, 1],
         [4, 0, 3],
         [0, 0, 1]],

        [[2, 1, 0],
         [0, 3, 1],
         [0, 1, 0]],

        [[1, 0, 3],
         [3, 1, 4],
         [1, 0, 0]],

        [[0, 3, 4],
         [1, 4, 4],
         [0, 0, 2]],

        [[3, 4, 3],
         [4, 4, 3],
         [0, 2, 3]],

        [[4, 3, 0],
         [4, 3, 4],
         [2, 3, 4]]],


       [[[3, 0, 4],
         [0, 4, 0],
         [4, 1, 4]],

        [[0, 4, 0],
         [4, 0, 0],
         [1, 4, 3]],

        [[4, 0, 3],
         [0, 0, 1],
         [4, 3, 0]],

        [[0, 3, 1],
         [0, 1, 0],
         [3, 0, 1]],

        [[3, 1, 4],
         [1, 0, 0],
         [0, 1, 0]],

        [[1, 4, 4],
         [0, 0, 2],
         [1, 0, 0]],

        [[4, 4, 3],
         [0, 2, 3],
         [0, 0, 2]],

        [[4, 3, 4],
         [2, 3, 4],
         [0, 2, 0]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [184]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
S

Symetric([[ 5, 15, 12, 11,  5],
          [15,  4,  9,  6,  7],
          [12,  9,  0, 42,  4],
          [11,  6, 42,  2, 11],
          [ 5,  7,  4, 11,  0]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [185]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [187]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [188]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

x = np.random.randint(0,2,(50,50))
for i in range(100): x = iterate(x)
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [189]:
x = np.arange(10000)
np.random.shuffle(x)
x[np.argsort(x)[-4:]]

array([9996, 9997, 9998, 9999])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [190]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

cartesian(([1, 2, 3], [4, 5], [6, 7]))

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★)

In [192]:
x = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
y = np.core.records.fromarrays(x.T, names='col1, col2, col3', formats = 'S8, f8, i8')
y

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [195]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([1, 2, 3, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [197]:
x = np.random.randint(0, 5, (10, 3))
print(x)
print('----')
tmp = np.all(x[:,1:] == x[:, :-1], axis=1)
y = x[~tmp]
print(y)

[[2 1 2]
 [4 0 4]
 [3 0 1]
 [1 0 2]
 [1 2 2]
 [4 4 0]
 [1 4 0]
 [3 3 2]
 [0 0 2]
 [1 4 4]]
----
[[2 1 2]
 [4 0 4]
 [3 0 1]
 [1 0 2]
 [1 2 2]
 [4 4 0]
 [1 4 0]
 [3 3 2]
 [0 0 2]
 [1 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [198]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
B[:,::-1]

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [200]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
uZ

array([[0, 1, 0],
       [0, 1, 1],
       [1, 0, 0]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [202]:
# np.einsum('i->', A) --> np.sum(A)
# np.einsum('i,i->i', A, B) --> A * B
# np.einsum('i,i', A, B) --> np.inner(A, B)
# np.einsum('i,j->ij', A, B) --> np.outer(A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [203]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)             
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)    
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [204]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
X[M]

array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [205]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
confint

array([-0.11061784,  0.25999931])